# Generated by Django 6.0.7 on 2026-07-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chiffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=40, verbose_name='Valeur')),
                ('libelle', models.CharField(max_length=120, verbose_name='Libellé')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Chiffre clé',
                'verbose_name_plural': 'Chiffres clés',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=150, verbose_name='Compétence')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Précision')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': "Domaine d'expertise",
                'verbose_name_plural': "Domaines d'expertise",
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Distinction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=250, verbose_name='Intitulé')),
                ('detail', models.CharField(blank=True, max_length=250, verbose_name='Détail')),
                ('annee', models.CharField(blank=True, max_length=40, verbose_name='Année')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Distinction & engagement',
                'verbose_name_plural': 'Distinctions & engagements',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200, verbose_name='Poste')),
                ('organisation', models.CharField(max_length=200, verbose_name='Organisation')),
                ('lieu', models.CharField(blank=True, max_length=120, verbose_name='Lieu')),
                ('periode', models.CharField(max_length=80, verbose_name='Période')),
                ('description', models.TextField(blank=True, help_text='Une mission par ligne. Chaque ligne devient une puce.', verbose_name='Missions')),
                ('en_cours', models.BooleanField(default=False, verbose_name='Poste actuel')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Du plus récent (0) au plus ancien.', verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Expérience professionnelle',
                'verbose_name_plural': 'Expériences professionnelles',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=250, verbose_name='Intitulé')),
                ('etablissement', models.CharField(blank=True, max_length=200, verbose_name='Établissement')),
                ('annee', models.CharField(max_length=40, verbose_name='Année')),
                ('mention', models.CharField(blank=True, max_length=120, verbose_name='Mention')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations et diplômes',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('organisation', models.CharField(blank=True, max_length=150, verbose_name='Organisation')),
                ('objet', models.CharField(max_length=200, verbose_name='Objet')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('envoye_le', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message reçu',
                'verbose_name_plural': 'Messages reçus',
                'ordering': ['-envoye_le'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom complet')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre principal')),
                ('sous_titre', models.CharField(blank=True, max_length=200, verbose_name='Fonction actuelle')),
                ('accroche', models.TextField(blank=True, verbose_name="Phrase d'accroche")),
                ('biographie', models.TextField(blank=True, verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, upload_to='portraits/', verbose_name='Portrait')),
                ('photo_credit', models.CharField(blank=True, max_length=250, verbose_name='Crédit photo')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse e-mail')),
                ('telephone', models.CharField(blank=True, max_length=60, verbose_name='Téléphone')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='X / Twitter')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
    ]
