# Generated by Django 6.0.7 on 2026-07-20 00:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Adresse')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Rubrique',
                'verbose_name_plural': 'Rubriques',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, help_text="Laisser vide : l'adresse est créée automatiquement à partir du titre.", max_length=220, unique=True, verbose_name='Adresse de la page')),
                ('chapo', models.TextField(blank=True, help_text="Résumé de deux ou trois lignes, affiché en tête d'article et dans la liste.", verbose_name='Chapô')),
                ('contenu', models.TextField(help_text='Écrivez normalement, en séparant les paragraphes par une ligne vide. Mise en forme facultative : **gras**, *italique*, ## Intertitre, [texte du lien](https://adresse).', verbose_name='Texte')),
                ('image', models.ImageField(blank=True, upload_to='articles/', verbose_name="Image d'illustration")),
                ('image_legende', models.CharField(blank=True, max_length=250, verbose_name="Légende de l'image")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon — visible de vous seule'), ('publie', 'Publié — visible par tous')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('publie_le', models.DateTimeField(default=django.utils.timezone.now, help_text='Une date future programme la parution.', verbose_name='Date de publication')),
                ('a_la_une', models.BooleanField(default=False, help_text="Affiche l'article en tête de la page Publications.", verbose_name='Mettre à la une')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('rubrique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='cv.rubrique', verbose_name='Rubrique')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-publie_le'],
            },
        ),
    ]
