# Generated by Django 6.0.7 on 2026-07-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_rubrique_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='image_fond',
            field=models.ImageField(blank=True, help_text="Vue de l'Assemblée nationale affichée derrière le titre d'accueil. Format paysage large, 1920 px minimum. Elle est fortement assombrie : seule la silhouette du bâtiment se devine.", upload_to='fonds/', verbose_name="Image d'arrière-plan"),
        ),
    ]
