# Generated by Django 6.0.7 on 2026-07-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_profil_image_fond'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='icone',
            field=models.CharField(choices=[('courbe', 'Courbe — management, pilotage'), ('bouclier', 'Bouclier — assurance, risques'), ('personnes', 'Personnes — social, communauté'), ('ecran', 'Écran — informatique, projets'), ('balance', 'Balance — gouvernance, politiques publiques'), ('coeur', 'Cœur — santé, prévention'), ('globe', 'Globe — international, partenariats'), ('document', 'Document — expertise, études')], default='courbe', max_length=20, verbose_name='Pictogramme'),
        ),
        migrations.AddField(
            model_name='experience',
            name='photo',
            field=models.ImageField(blank=True, help_text="Facultatif : une photo prise pendant cette fonction — cérémonie, mission de terrain, signature d'accord. Format paysage de préférence. La fiche s'affiche très bien sans photo.", upload_to='experiences/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='experience',
            name='photo_legende',
            field=models.CharField(blank=True, help_text='Décrire la scène : lieu, événement, date.', max_length=250, verbose_name='Légende de la photo'),
        ),
    ]
