# Generated by Django 6.0.7 on 2026-07-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_competence_icone_experience_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=220, verbose_name='Titre')),
                ('domaine', models.CharField(choices=[('protection', 'Protection sociale et santé'), ('jeunesse', 'Jeunesse et emploi'), ('territoires', 'Développement des territoires'), ('parlement', 'Travail parlementaire'), ('reconnaissance', 'Reconnaissances')], default='protection', max_length=20, verbose_name='Domaine')),
                ('annee', models.CharField(help_text='Par exemple « 2022 » ou « 2020-2024 ».', max_length=40, verbose_name='Année ou période')),
                ('description', models.TextField(help_text='Deux à quatre phrases.', verbose_name='Description')),
                ('chiffre', models.CharField(blank=True, help_text='Facultatif : « 1 852 projets », « 500 000 assurés »…', max_length=60, verbose_name='Chiffre à mettre en avant')),
                ('chiffre_libelle', models.CharField(blank=True, max_length=120, verbose_name='Précision du chiffre')),
                ('photo', models.ImageField(blank=True, upload_to='realisations/', verbose_name='Photo')),
                ('photo_legende', models.CharField(blank=True, max_length=250, verbose_name='Légende de la photo')),
                ('source_url', models.URLField(help_text='Article de presse ou page officielle attestant de cette réalisation.', verbose_name='Lien de la source')),
                ('source_nom', models.CharField(help_text='Par exemple « République Togolaise » ou « Agence Ecofin ».', max_length=120, verbose_name='Nom de la source')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations et engagements',
                'ordering': ['ordre'],
            },
        ),
    ]
