# Generated by Django 6.0.7 on 2026-07-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_realisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galerie/', verbose_name='Photo')),
                ('legende', models.CharField(blank=True, help_text='Décrire la scène : lieu, événement, date.', max_length=250, verbose_name='Légende')),
                ('date', models.CharField(blank=True, help_text='Facultatif, par exemple « Juin 2024 ».', max_length=60, verbose_name='Date ou période')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Photo de la galerie',
                'verbose_name_plural': 'Galerie',
                'ordering': ['ordre'],
            },
        ),
    ]
