# Generated by Django 6.0.7 on 2026-07-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='credit',
            field=models.CharField(blank=True, help_text='Auteur de la photo. Obligatoire pour une image sous licence Creative Commons.', max_length=200, verbose_name='Crédit / auteur'),
        ),
        migrations.AddField(
            model_name='photo',
            name='fichier_statique',
            field=models.CharField(blank=True, help_text='Réservé aux images fournies avec le site. Laisser vide pour un téléversement.', max_length=200, verbose_name='Fichier livré'),
        ),
        migrations.AddField(
            model_name='photo',
            name='licence',
            field=models.CharField(blank=True, help_text='Par exemple « CC BY 4.0 ». À laisser vide pour les photos de votre cabinet.', max_length=60, verbose_name='Licence'),
        ),
        migrations.AddField(
            model_name='photo',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Lien de la source'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='galerie/', verbose_name='Photo (téléversée)'),
        ),
    ]
