# Generated by Django 6.0.7 on 2026-07-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_photo_credit_photo_fichier_statique_photo_licence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='photo_credit',
            field=models.CharField(blank=True, help_text='Auteur ou source du cliché (ex. « Cabinet / Ministère »).', max_length=200, verbose_name='Crédit de la photo'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='photo_fichier',
            field=models.CharField(blank=True, help_text='Réservé aux images fournies avec le site. Laisser vide pour un téléversement.', max_length=200, verbose_name='Photo livrée (fichier)'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='photo',
            field=models.ImageField(blank=True, upload_to='realisations/', verbose_name='Photo (téléversée)'),
        ),
    ]
