# Generated by Django 6.0.7 on 2026-08-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_realisation_photo_credit_realisation_photo_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='profil',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='profil',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
    ]
