# Generated by Django 6.0.7 on 2026-08-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_profil_facebook_profil_instagram_profil_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='distinction',
            name='photo',
            field=models.ImageField(blank=True, upload_to='distinctions/', verbose_name='Photo (téléversée)'),
        ),
        migrations.AddField(
            model_name='distinction',
            name='photo_credit',
            field=models.CharField(blank=True, help_text='Auteur ou source du cliché.', max_length=200, verbose_name='Crédit de la photo'),
        ),
        migrations.AddField(
            model_name='distinction',
            name='photo_fichier',
            field=models.CharField(blank=True, help_text='Réservé aux images fournies avec le site. Laisser vide pour un téléversement.', max_length=200, verbose_name='Photo livrée (fichier)'),
        ),
        migrations.AddField(
            model_name='distinction',
            name='photo_legende',
            field=models.CharField(blank=True, max_length=250, verbose_name='Légende de la photo'),
        ),
    ]
