# Generated by Django 6.0.7 on 2026-08-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_distinction_photo_distinction_photo_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Lien de la source'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='tiktok',
            field=models.URLField(blank=True, max_length=500, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='twitter',
            field=models.URLField(blank=True, max_length=500, verbose_name='X / Twitter'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='source_url',
            field=models.URLField(help_text='Article de presse ou page officielle attestant de cette réalisation.', max_length=500, verbose_name='Lien de la source'),
        ),
    ]
