# Generated by Django 6.0.7 on 2026-08-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_alter_photo_source_url_alter_profil_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_fichier',
            field=models.CharField(blank=True, help_text='Réservé aux images fournies avec le site. Laisser vide pour un téléversement.', max_length=200, verbose_name='Image livrée (fichier)'),
        ),
    ]
