# Generated by Django 6.0.7 on 2026-08-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_article_image_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=220, verbose_name='Titre de la vidéo')),
                ('youtube_url', models.URLField(max_length=500, verbose_name='Lien YouTube')),
                ('youtube_id', models.CharField(blank=True, max_length=50, verbose_name='ID YouTube')),
                ('est_short', models.BooleanField(default=False, verbose_name='Format Short (vertical)')),
                ('thematique', models.CharField(choices=[('parlement', 'Travail parlementaire'), ('protection', 'Protection sociale & AMU'), ('jeunesse', 'Jeunesse & Développement'), ('discours', 'Discours & Événements')], default='parlement', max_length=30, verbose_name='Thématique')),
                ('date', models.CharField(blank=True, max_length=60, verbose_name='Date ou période')),
                ('legende', models.CharField(blank=True, max_length=250, verbose_name='Description / Légende')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos de la galerie',
                'ordering': ['ordre'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='chapo',
            field=models.TextField(blank=True, help_text="Résumé de deux ou trois lignes, affiché en tête d'article et dans la liste.", verbose_name='Résumé'),
        ),
    ]
