# Generated by Django 6.0.7 on 2026-08-24 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_video_alter_article_chapo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAutorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail autorisée')),
                ('nom_utilisateur', models.CharField(blank=True, max_length=120, verbose_name='Nom / Titulaire')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
            ],
            options={
                'verbose_name': 'E-mail autorisé',
                'verbose_name_plural': 'E-mails autorisés (Whitelist 2FA)',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='CodeSecurite2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code à 6 chiffres')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expire_le', models.DateTimeField(verbose_name='Expire le')),
                ('est_utilise', models.BooleanField(default=False, verbose_name='Est utilisé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code 2FA',
                'verbose_name_plural': 'Codes 2FA',
                'ordering': ['-cree_le'],
            },
        ),
    ]
