# Generated by Django 6.0.7 on 2026-09-21 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_emailautorise_codesecurite2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fichier',
            field=models.FileField(blank=True, help_text='MP4 recommandé (lisible sur tous les appareils).', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'm4v'])], verbose_name='Fichier vidéo'),
        ),
        migrations.AddField(
            model_name='video',
            name='vignette',
            field=models.ImageField(blank=True, help_text="Facultatif : image affichée avant la lecture d'un fichier vidéo.", upload_to='videos/apercus/', verbose_name="Image d'aperçu"),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Renseigner soit un lien YouTube, soit un fichier vidéo.', max_length=500, verbose_name='Lien YouTube'),
        ),
    ]
