# Generated by Django 6.0.7 on 2026-10-04 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_video_fichier_video_vignette_alter_video_youtube_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppareilDeConfiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton', models.CharField(max_length=64, unique=True, verbose_name="Jeton d'appareil")),
                ('adresse_ip', models.GenericIPAddressField(verbose_name='Adresse IP validée')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Navigateur / appareil')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Validé le')),
                ('derniere_connexion_le', models.DateTimeField(auto_now=True, verbose_name='Dernière connexion')),
                ('expire_le', models.DateTimeField(verbose_name='Expire le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils_confiance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appareil de confiance',
                'verbose_name_plural': 'Appareils de confiance',
                'ordering': ['-derniere_connexion_le'],
            },
        ),
    ]
